### ISSUE TITLE
Task addition dialog

### ISSUE THREAD

**Issue by muness** [cloud-atlas-ai/obsidian-am#18]
Per facebook announcement [convo](https://www.facebook.com/groups/1927874704161821/posts/3669954219953852/?comment_id=3670121043270503&reply_comment_id=3670136343268973):

> Use Case 1) I'm taking notes in Obsidian, let's say in a meeting, and I want to have a task to do something with start, scheduled, due dates. I want to run a "Create Marvin Task" command in Obsidian that pulls up the Categories/Projects from my master list to select from and has me enter the standard Marvin task details including the shorthand like + or @ or ~ and it translates correctly (kind of like what you can do in the subject line when forwarding an email to Marvin address). When I hit enter I have a link to the Marvin deep link task in Obsidian at the cursor spot, and the Marvin task contains an Advanced URI-friendly link back to Obsidian note that drove the task.

- [x] Dialog to add tasks
- [x] Autocomplete Category or Project based on `#` syntax or a Search sub-dialog
- [x] Make `+` `@` `~` behave as with additions in the Amazing Marvin app.
- [x] Add task in AM

Reference:
- [Create a Task API](https://github.com/amazingmarvin/MarvinAPI/wiki/Marvin-API#create-a-task)

**Comment by judisohn** [comment]
Hi @muness I'm the one you've been chatting with about this on FB... happy to test this via BRAT whenever you're ready for a ~~guinea pig~~ tester. I'm watching the repo or feel free to ping.

**Comment by judisohn** [comment]
> Add link back to Obsidian Note that triggered the addition, perhaps in the note field

Definitely picturing in the note field, as an append. Perhaps app settings in Obsidian could have a template config for the field so a header could be customized?

**Comment by muness** [comment]
Good progress, linking back in the note is yet tbd, so is inferring the category if a task is created from one.

**Comment by muness** [comment]
@judisohn - please give https://github.com/cloud-atlas-ai/obsidian-am/releases/tag/0.5.0b1 a try for task creation from AM will add advanced-uri link back to Obsidian when I get back to this later this week.

**Comment by judisohn** [comment]
@muness I tried. I downloaded the .zip file from https://github.com/cloud-atlas-ai/obsidian-am/releases/tag/0.5.0b1 and added it to my .obsidian directory. 

![CleanShot 2023-12-26 at 08 16 20@2x](https://github.com/cloud-atlas-ai/obsidian-am/assets/4614343/3a854827-6aa5-4cc1-ba3e-9b9b68a52cbb)

I restart Obsidian so I see it, but I get an error when I try and enable it. What did I miss?

https://github.com/cloud-atlas-ai/obsidian-am/assets/4614343/300e886f-21f3-4f35-8a3c-c720ff32cb91

**Comment by judisohn** [comment]
I do notice you're missing a `main.js` file that other plugins have. Could that be it?

**Comment by muness** [comment]
@judisohjig if you're not using BRAT you want to grab the `cloudatlas-o-am.zip` file. Sounds like you got the source zip file that github adds automatically.

**Comment by judisohn** [comment]
Duh @muness - of course. That's what I get for playing with something before my first coffee. Got it and enabled it. Trying it now. :-) Stay tuned for notes and feedback. Thank you!

**Comment by judisohn** [comment]
@muness Tried it (with API token, not full access token - at least first)

- I used `Create Marvin Tasks` and got exactly what I hoped to see. A task at the cursor mark. I assume the `::` at the end of dates is for Dataview?
- I created some tasks in Marvin for testing and then used `Import Today's Tasks` 
 - It imported the tasks in a `## Tasks` Header which is good
 - When I marked a task as completed it did not seem to update in Marvin, even after running the import command again
 - When running the command again, I got a new Tasks header with the same tasks

So it would be great if it could detect that a Tasks header already exists and modify it as I can picture running this more than once in my day and things are updated and changed in Marvin. What do you think?

I can also picture the ability to only import tasks that match a given category rather than everything, but this is a good start for now. Thanks!

P.S. I don't see myself needing an entire AmazingMarvin folder in my vault, so I didn't test or use that command.

**Comment by muness** [comment]
> When I marked a task as completed it did not seem to update in Marvin, even after running the import command again

Did you enable the auto mark as done feature in settings? If you did was there an error?

**Comment by judisohn** [comment]
Yes, I did enable it. And yes, there was an error when I loaded the dev console. Sorry I'm not a developer so I don't know where to get this into a more readable format for you. This error happened when I clicked the "Insert" command a 2nd time after marking one of the first tasks complete (and I got a 2nd Task block)

![CleanShot 2023-12-26 at 09 00 33@2x](https://github.com/cloud-atlas-ai/obsidian-am/assets/4614343/dea8f202-fa03-4d45-8ca9-6b8d50f7f9c9)

**Comment by muness** [comment]
Looks like I should spend time improving the error handling and messages before I add more functionality, thanks for giving it a try.

By the way did you enable the local server? It looks like that error was about not being able to connect to that.

As for updating the Tasks section instead of adding a new one, I agree. There's another issue for overhauling that. Ditto for making formatting configurable (the `::` is indeed for Dataview, but not everyone wants that).

**Comment by judisohn** [comment]
I've tried to enable the local server, but every time I do and go back to it, it's unchecked again. What am I missing? Nothing about this is showing up in the log.

**Comment by muness** [comment]
Doh, one more thing to fix it sounds like. It sounds like I forgot to persist the local server toggle properly.

**Comment by judisohn** [comment]
No worries.. let me know when there's a new version to try out. If nothing else, I love that I can get a Marvin task created right from Obsidian while it's on my mind and the link back to the task works great. I know you'll get the rest and you're off to a great start. Happy to be on the journey with you for something so needed (at least so needed by me. :-) )

**Comment by muness** [comment]
- Fixed the issue with the local server toggle in https://github.com/cloud-atlas-ai/obsidian-am/pull/20 . It turns out it was getting set, I just wasn't displaying it correctly.
- Improved the Add Task dialog in https://github.com/cloud-atlas-ai/obsidian-am/pull/21.
  - Defaults to Inbox category.
  - Won't just fail silently if no category is selected.
  - Support Ctrl-Enter to create the task without having to click the Add button or tab over to it.
  - Won't just fail silently if no Task text is added. Instead shows an error notice.
- Created https://github.com/cloud-atlas-ai/obsidian-am/issues/22 to track the failing Mark as Done. I wasn't able to reproduce it.
- Created https://github.com/cloud-atlas-ai/obsidian-am/issues/23 to implement the Update Tasks instead of re-adding them (in Daily Notes) or overwriting the notes altogether (in Import).

**Comment by muness** [comment]
Created #24 , #25 , #26 for remaining tasks, closing this issue as it was about the basic task addition functionality.
