### ISSUE TITLE
Link back to Advanced URI link is not clickable/properly formatted

### ISSUE THREAD

**Issue by judisohn** [cloud-atlas-ai/obsidian-am#35]
@muness There is an issue with the Advanced URI link that is saved in the Note on the Marvin Task. 

This is what it is showing as:

```
[🏷️](obsidian://advanced-uri?filePath=Periodic Notes/Daily Notes/2023-12-27.md&vault=MyVault)
```

But that is the wrong format for Advanced URI. When I copy the Advanced URI from Obsidian, it's this:

```
obsidian://advanced-uri?vault=MyVault&filepath=Periodic%2520Notes%252FDaily%2520Notes%252F2023-12-27.md
```
It also doesn't need the `[ ]( )` Markdown. It is only clickable for me if it's just the file link.

**Comment by muness** [comment]
Ah, I should url encode the link as it has spaces. I didn't notice as I don't have spaces in filenames.

The markdown link worked for me. I'll check that too or switch to just the link.

**Comment by muness** [comment]
@judisohn , can you check that the link works as of https://github.com/cloud-atlas-ai/obsidian-am/releases/tag/0.5.2 ? Thanks!

**Comment by judisohn** [comment]
@muness I have 0.5.2 but no difference in the URL generated from the previous version. Did I miss something?

![CleanShot 2023-12-27 at 21 41 15@2x](https://github.com/cloud-atlas-ai/obsidian-am/assets/4614343/edadcd5e-9261-4c44-9b28-64d8110f0a1b)

![CleanShot 2023-12-27 at 21 41 37@2x](https://github.com/cloud-atlas-ai/obsidian-am/assets/4614343/f2bb0c6c-6d9c-4dba-a60d-c2892031af87)

**Comment by muness** [comment]
My apologies, @judisohn  I made a mistake in the 0.5.2 release 🤦  https://github.com/cloud-atlas-ai/obsidian-am/releases/tag/0.5.3 is actually right.

**Comment by judisohn** [comment]
There's no strategy that includes "Markdown." I'd love it. Other Markdown is fine... such as `[Page Name](https://...)` but somehow for me, it doesn't resolve when it's a file link. I'll grab 0.5.3 now and see if it improves the situation.

**Comment by judisohn** [comment]
It worked! As I thought, when the link was fixed it resolved as Markdown... 

<img width="347" alt="CleanShot 2023-12-28 at 10 58 41@2x" src="https://github.com/cloud-atlas-ai/obsidian-am/assets/4614343/32b630ac-b925-4492-97a2-061d05301dd4">

But, it would be great if we could edit this... that tiny tag icon is a pain to target with the mouse and I'd prefer something like "Obsidian Link" rather than just an icon. Or frankly, the full link because when in full view, it's much harder to see the full path and you're clicking that little tag on trust alone. 

Ugh, but sadly... clicking to mark the task as done is once again not working and failing silently. :-( The only thing I changed between this time and last is that I used BRAT rather than manually downloading the files. It's showing the right 0.5.3 version so not sure if that would make a difference?

**Comment by muness** [comment]
Maybe we should make the link configurable.

I'll also double check that my messed up merge didn't mess up mark as done.

**Comment by muness** [comment]
No luck reproducing the Mark As Done issue, @judisohn . I have the Tasks Plugin enabled and it's adding the done date on checking them off. Can you start a new issue with any details you have about your setup : which task plugins you're using and how they're configured.

**Comment by judisohn** [comment]
@muness Good news is that with 0.5.4b it's trying to mark the task as done. Bad news is that it won't due to the all-too-familiar `status 429` error.

**Comment by muness** [comment]
Hopefully we'll hear back about how to best proceed re the 429s soon. I could add a caching layer, but that will likely cause all kinds of unexpected behavior.
